### ISSUE TITLE
draft-pdf.yml gives error

### ISSUE THREAD

**Issue by dicaearchus** [GO-Eratosthenes/dhdt#66]
it gives:

[Paper Draft](https://github.com/GO-Eratosthenes/dhdt/actions/runs/4224816551/jobs/7336261364)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by fnattino** [comment]
This seems to be a warning (it is also shown for the other actions, e.g. `build`).

The error in generating the PDF seems to be [here](https://github.com/GO-Eratosthenes/dhdt/actions/runs/4224816551/jobs/7336261364#step:4:1077):

```
Error producing PDF.
! LaTeX Error: File `dirtree.sty' not found.
```

**Comment by dicaearchus** [comment]
resolved via 828c662887f50d90f84777ac1bcc1a5c7dadb69a

**Comment by fnattino** [comment]
Did this actually solve the issue? I see the last action run still failed

**Comment by dicaearchus** [comment]
You are right, I was too fast on pushing this off the desk :)

**Comment by fnattino** [comment]
Opened the following issue: https://github.com/openjournals/inara/issues/28
